# Variables to access Twitter API
ACCESS_TOKEN = "YOUR_ACCES_TOKEN_HERE"
ACCESS_TOKEN_SECRET = "YOUR_SECRET_ACCES_TOKEN_HERE"
CONSUMER_KEY = "YOUR_CONSUMER_KEY_HERE"
CONSUMER_SECRET = "YOUR_CONSUMER_ACCESS_KEY_HERE"
